//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharmusiq.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareRequest
    {
        public ShareRequest()
        {
            this.ShareResponses = new HashSet<ShareResponse>();
        }
    
        public int Id { get; set; }
        public System.DateTime ShareDate { get; set; }
    
        public virtual Track Track { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ShareResponse> ShareResponses { get; set; }
    }
}
