//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharmusiq.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareResponse
    {
        public int Id { get; set; }
        public System.DateTime ResponseDate { get; set; }
        public Nullable<bool> Acknowledged { get; set; }
        public string Message { get; set; }
    
        public virtual ShareRequest ShareRequest { get; set; }
    }
}
