//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharmusiq.API.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMDbContainer : DbContext
    {
        public SMDbContainer()
            : base("name=SMDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<ShareRequest> ShareRequests { get; set; }
        public virtual DbSet<ShareResponse> ShareResponses { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TrackFeature> TrackFeatures { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
    }
}
