//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharmusiq.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.TrackFeatures = new HashSet<TrackFeature>();
            this.ShareRequests = new HashSet<ShareRequest>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Artist { get; set; }
        public string Genre { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
    
        public virtual ICollection<TrackFeature> TrackFeatures { get; set; }
        public virtual ICollection<ShareRequest> ShareRequests { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
