//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharmusiq.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRoles = new HashSet<UserRoles>();
            this.ShareRequests = new HashSet<ShareRequest>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsIdentityDelegated { get; set; }
        public string ProviderName { get; set; }
        public string ProviderUserKey { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> FirstAccessDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
    
        public virtual ICollection<UserRoles> UserRoles { get; set; }
        public virtual ICollection<ShareRequest> ShareRequests { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
